Add save callback and buttons to NAD viewer
powsybl/powsybl-network-viewer pull request #121
Opened 2024-11-06 09:48 UTC by massimo-ferraro

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
no

**What kind of change does this PR introduce?**
feature

**What is the current behavior?**
In network area diagram viewer it is not possible to save updated SVG or metadata. 
By default the mouse is used for moving nodes. For selecting nodes the SHIFT key must be used.

**What is the new behavior (if this is a feature change)?**
A callback for saving SVG and metadata has been added.
Three buttons can be added to the viewer, two buttons for changing between moving nodes and selecting nodes, and one button for calling the save callback

**Does this PR introduce a breaking change or deprecate an API?**
- [X] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [X] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**
the constructor of the NetworkAreaDiagramViewer has 3 additional parameters:
- the save callback
- the flag for enabling the visualization of the buttons
- the default action for the mouse: moving vs. selection

Examples are provided in the demo/src/diagram-viewers/add-diagrams.js file

2024-11-07 16:49 UTC, flo-dup requested changes

2024-11-08 09:05 UTC, massimo-ferraro commented on src/components/network-area-diagram-viewer/diagram-utils.ts
> +        button.style.boxShadow = 'none';
done

2024-11-08 09:05 UTC, massimo-ferraro commented on src/components/network-area-diagram-viewer/diagram-utils.ts
> +        button.style.boxShadow = '0px 1px 2px rgba(0, 0, 0, 1)';
done

2024-11-08 09:06 UTC, massimo-ferraro commented on src/components/network-area-diagram-viewer/diagram-utils.ts
> +    button.style.marginTop = '1px';
done

2025-03-20 21:49 UTC, massimo-ferraro commented
Outdated code, some code of this PR will no more be used, some code has been re-used in other PRs

2025-03-20 21:49 UTC, closed without merging